# Generated by Django 4.0.5 on 2022-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazimtaani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='siteurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
