# Generated by Django 4.0.5 on 2022-06-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazimtaani', '0002_job_siteurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('internship', 'Internship')], max_length=15),
        ),
    ]
