# Generated by Django 3.2.2 on 2022-06-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazimtaani', '0002_job_siteurl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('location', 'category')},
        ),
    ]
